# Generated by Django 3.2.23 on 2023-11-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20231115_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
