# Generated by Django 3.2.23 on 2023-11-15 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
